version: '3.8'
services:
  ciga-algorithms:
    image: ciga-algorithms
    container_name: ciga-algorithms
    build: .
    ports:
      - 5000:5000
    networks:
      - barramento_static-network
    restart: unless-stopped
    volumes:
      - ./logs/:/app/logs/
networks:
  barramento_static-network:
    external:
      name: barramento_static-network
